#!/bin/bash

## AUGUSTUS parallel execution:
## This program will take a multi fasta file and chop it in equal pieces
## according to the number of processes supplied for parameter -j. Be aware
## that AUGUSTUS is greedy when it comes to memory. Parallel running of
## AUGUSTUS is achieved with GNU parallel.
## Requirements: conda environment with augustus named augustus
##
## Tange, O., 2020, GNU Parallel 20201122 ('Biden'), Zenodo, https://doi.org/10.5281/zenodo.4284075

### Get the directory where the program is located
home=/mnt/data/arslan/tool/Augustus-3.5.0/scripts/

### Standard path for a miniconda3 install
miniconda=/mnt/data/arslan/tool/miniconda3/etc/profile.d/conda.sh

### Check if miniconda3 is install and if yes activate it
if [[ -f "$miniconda" ]]; then
    echo "$miniconda exists."
    source $miniconda
else
    echo -e "[error]\tCould not find miniconda install."
    exit 1
fi

### Helpfunction in case something goes wrong
helpFunction()
{
   echo ""
   echo "Run AUGUSTUS in parallel."
   echo "The AUGUSTUS parameter --uniqueGeneId and --gff3 is set to true by default (necessary)."
   echo ""
   echo "Usage: $(basename -- "$0") -f fasta.file.fa -c threads -p AUGUSTUS_parameters"
   echo ""
   echo -e "\t-f Path to fasta file.fa (mandatory)"
   echo -e "\t-c Number of CPU cores to use (be careful with memory consumption of AUGUSTUS)"
   echo -e "\t-p AUGUSTUS parameters: e.g. '--species=arabidopsis,--UTR=on,--progress=true'"
   echo -e "\t-o Output path (full): /home/user/analysis"
   echo ""
   exit 1 # Exit script after printing help
}

# Parse the parameters
while getopts "c:f:p:o:" opt
do
   case "$opt" in
      c ) parameterC="$OPTARG" ;;
      f ) parameterF="$OPTARG" ;;
      p ) parameterP="$OPTARG" ;;
      o ) parameterO="$OPTARG" ;;
      ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent
   esac
done

### Checking the parameters
if [ ! -f "$parameterF" ]
then
   echo -e "[error]\tNo fasta file supplied.";
   helpFunction
fi

if [ -z "$parameterC" ]
then
   echo -e "[warning]\tNo -c set. Defaulting to 1.";
   parameterC=1
fi

if [ -z "$parameterP" ]
then
   echo -e "[warning]\tNo AUGUSTUS parameters given";
   helpFunction
fi

#### Check the output folder: if non is supplied results will be saved in fasta
#### directory
if [ -z "$parameterO" ]
then
  # If nothing is supplied use fasta path
  echo -e "[warning]\tNo output path indicated: defaulting to $(dirname $parameterF)"
  wd=$(dirname $parameterF)
else
  # If a output path is supplied use it
  wd=$parameterO
fi

### End parameter check

### Activate the AUGUSTUS conda environment
conda activate augustus-env

### Convert the supplied AUGUSTUS parameters from e.g. '--species=arabidopsis,--gff3=on'
### to '--species=arabidopsis --gff3=on' and save them in parameterA
### Also check if output is going to be gff3 or standard gtf
IFS=','
for x in $parameterP
do
  parameterA+=" "$x
done

file_name=$(basename -- $parameterF)

echo -e "[info]\tWorking dir:          $wd"
echo -e "[info]\tOutput dir:           $parameterO"
echo -e "[info]\tCPUs:                 $parameterC"
echo -e "[info]\tFasta:                $parameterF"
echo -e "[info]\tAUGUSTUS parameters:  $parameterA"
echo -e "[info]\tGFF3 mode:            $gff3_mode"

### Create a temporary folder to save the fasta chuncks
mkdir $wd"/tmp/"


sed '/^>/ s/ .*//' $parameterF >${parameterF%.*}_mod.fa
GENOME=${parameterF%.*}_mod.fa
splitMfasta.pl  $GENOME --outputpath=$wd"/tmp/"

### Rename of split files with contig name. 

cd $wd/tmp/
for f in ${GENOME%.*}.split.*; do NAME=`grep ">" $f`; mv $f ${NAME#>}.fa;done

### Save path of generated fasta file chuncks
chunck_files=$wd"/tmp/"*.fa

### If gff3 mode is enabled for augustus give it a different output file ending
IFS=' '
for f in $chunck_files
do
    file=$(basename -- $f)
    echo -e "augustus$parameterA --uniqueGeneId=true --gff3=on $f > ${wd}/tmp/${file}.gff3" >> $wd"/tmp/aug_cmd.txt"
done


cat $wd"/tmp/aug_cmd.txt" | parallel -j $parameterC --joblog $wd"/tmp/Aug.parallel.log"

### Concatenate all GFF3 files into one
chunck_gff3=$wd"/tmp/"*.gff3
touch $wd"/"$file_name".aug.gff3"
for f in $chunck_gff3
do
  cat $f >> $wd"/"$file_name".aug.gff3"
done

### Use the AUGUSTUS perl script getAnnoFasta.pl to extract the mRNA, cds and
### Protein sequences of the predicted genes
getAnnoFasta.pl --seqfile=$parameterF $wd"/"$file_name".aug.gff3"

conda deactivate
rm -rf $wd/tmp


echo "#########################################################"
echo "#########################################################"
echo "#########################################################"
echo "                                                         "
echo "            Good bye, I am going to sleep :)             "
echo "                                                         "
echo "#########################################################"
echo "#########################################################"
echo "#########################################################"
